
version: "2"

linters:
  enable:
    - revive
    - errcheck
    - unparam
    - ineffassign

linters-settings:
  revive:
    config: .revive.toml

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/UCLALibrary/validation-service
