//go:build unit

package api

import (
	"flag"
	"fmt"
	"github.com/UCLALibrary/validation-service/testflags"
	"testing"
)

// TestAPI loads the flags for the tests in the 'api' package.
func TestAPI(t *testing.T) {
	flag.Parse()
	fmt.Printf("%s's log level: %s\n", t.Name(), *testflags.LogLevel)
}

// TestForTheSakeOfSuccess is a simple brain-dead test that just prevents the build from failing for lack of tests.
//
// We don't actually test anything in the 'api' package. It's all code autogenerated by the oapi-codegen tool.
func TestForTheSakeOfSuccess(t *testing.T) {
	_, err := GetSwagger()
	if err != nil {
		t.Errorf("GetSwagger() error = %v", err)
	}
}
