//go:build unit
package api

import (
	"testing"
)

// TestForTheSakeOfSuccess is a simple brain-dead test that just prevents the build from failing for lack of tests.
//
// We do not test anything in the 'api' package. It's all code autogenerated by the oapi-codegen tool.
func TestForTheSakeOfSuccess(t *testing.T) {
	_, err := GetSwagger()
	if err != nil {
		t.Errorf("GetSwagger() error = %v", err)
	}
}
