//go:build unit

// Package api consists of API handling code.
//
// This file sets up the testing environment for the tests.
package api

import (
	"testing"
)

// TestForTheSakeOfSuccess is a simple brain-dead test that just prevents the build from failing for lack of tests.
//
// We don't actually test anything in the 'api' package. It's all code autogenerated by the oapi-codegen tool.
func TestForTheSakeOfSuccess(t *testing.T) {
	_, err := GetSwagger()
	if err != nil {
		t.Errorf("GetSwagger() error = %v", err)
	}
}
