
name: CI Test

# Defines environmental variables
env:
  GO_VERSION: '1.23.3'
  GO_LINTER_VERSION: 'v1.62.0'

# Controls when the action will run
on:
  pull_request:
    branches:
      - main

# A series of workflow jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build and Test

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout source
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    # Setup the Go environment
    - name: Setup Go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      with:
        go-version: "${{ env.GO_VERSION }}"

    - name: Install Go linter
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | \
          sh -s -- -b $(go env GOPATH)/bin ${{ env.GO_LINTER_VERSION }}

    # Build and test the application (also lints)
    - name: Build Docker container
      run: make all
