
name: CI Test

# Defines environmental variables
env:
  GO_VERSION: '1.22.2'
  SERVICE_NAME: 'validation-service'

# Controls when the action will run
on:
  pull_request:
    branches:
      - main

# A series of workflow jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build and Test

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout source
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    # Setup the Go environment
    - name: Setup Go
      uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
      with:
        go-version: "${{ env.GO_VERSION }}"

    # Build the container so TestContainers has something to run
    - name: Build Docker container
      run: docker build -t "${{ env.SERVICE_NAME }}" .

    # Run the tests
    - name: Test with the Go CLI
      run: go test
