name: Build and Publish Docker Image

env:
    GO_VERSION: '1.22.4'
    SERVICE_NAME: 'service-template'
    ALPINE_VERSION: '3.20'

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@aa33708b10e362ff993539393ff100fa93ed6a27 # v3.5.0

    - name: Optionally, login to Docker repository
      uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      if: env.DOCKER_USERNAME != null
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@1ca370b3a9802c92e886402e0dd88098a2533b12 # v6.4.1
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ vars.DOCKER_REGISTRY_ACCOUNT }}/${{ env.SERVICE_NAME }}:${{ github.ref_name }}
        build-args: |
          GO_VERSION=${{ env.GO_VERSION }}
          ALPINE_VERSION=${{ env.ALPINE_VERSION }}
          SERVICE_NAME=${{ env.SERVICE_NAME }}
        labels: |
          org.opencontainers.image.source=https://github.com/uclalibrary/${{ env.SERVICE_NAME }}
          org.opencontainers.image.description=UCLA Library's ${{ env.SERVICE_NAME }}
