name: Build and Publish Docker Image

env:
    GO_VERSION: '1.22.4'
    SERVICE_NAME: 'validation-service'
    ALPINE_VERSION: '3.20'

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0

    - name: Optionally, login to Docker repository
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      if: env.DOCKER_USERNAME != null
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ vars.DOCKER_REGISTRY_ACCOUNT }}/${{ env.SERVICE_NAME }}:${{ github.ref_name }}
        build-args: |
          GO_VERSION=${{ env.GO_VERSION }}
          ALPINE_VERSION=${{ env.ALPINE_VERSION }}
          SERVICE_NAME=${{ env.SERVICE_NAME }}
        labels: |
          org.opencontainers.image.source=https://github.com/uclalibrary/${{ env.SERVICE_NAME }}
          org.opencontainers.image.description=UCLA Library's ${{ env.SERVICE_NAME }}
